apiVersion: v1
kind: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: dev
  labels:
    app: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
         app : node-app
    spec:
      containers:
        - name: node-app
          image: toto1337/node:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: 8080


